title: Quincy Powell
description: SEO Strategist and Digital Content Specialist portfolio
author:
  name: Quincy Powell

theme: minima

url: "https://quincyjpowell.github.io"
baseurl: ""

header_pages:
  - about.md
  - projects.md
  - resume.md
  - contact.md

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-feed

social:
  links:
    - https://github.com/quincyjpowell
